AllCops:
  Excludes:
    - 'Guardfile'
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false
# Enforce the method used for string formatting.
Style/FormatString:
  EnforcedStyle: sprintf
  SupportedStyles:
    - format
    - sprintf
    - percent

Style/FrozenStringLiteralComment:
  Enabled: false
